name: Run Tests and Deploy Allure Report

on:
  schedule:
    - cron: '0 0 * * *'    # Щоденний запуск тестів
  workflow_dispatch:        # Можливість запускати вручну
    inputs:
      test_name:
        description: 'Path to test file or test name (example: app/test1.py -k test_test)'
        required: false
        default: ''

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Allure Command Line (using Homebrew)
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -sSL https://install.github.com/homebrew.sh | bash
        brew install allure

    - name: Run tests
      run: |
        if [ -z "${{ github.event.inputs.test_name }}" ]; then
          pytest app/test1.py --alluredir=allure-results
        else
          pytest ${{ github.event.inputs.test_name }} --alluredir=allure-results
        fi

    - name: Generate Allure Report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Deploy Allure Report to Cloud Run
      run: |
        gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=${{ secrets.GCP_SA_KEY }}
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report
        gcloud run deploy allure-report \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
