name: Run Tests and Deploy Allure Report

on:
  schedule:
    - cron: '0 0 * * *'    # Щоденний запуск тестів о 00:00 UTC
  workflow_dispatch:        # Можливість запускати вручну
    inputs:
      test_name:
        description: 'Test name or pattern (pytest -k)'
        required: false
        default: ''

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Run tests
      run: |
        pytest -k "${{ github.event.inputs.test_name }}" --alluredir=allure-results

    - name: Generate Allure Report
      run: |
        pip install allure-commandline
        allure generate allure-results -o allure-report --clean

    - name: Deploy Allure Report to Cloud Run
      run: |
        gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=${{ secrets.GCP_SA_KEY }}
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report
        gcloud run deploy allure-report \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
