name: Run Tests and Deploy Allure Report

on:
  schedule:
    - cron: '0 0 * * *'    # Щоденний запуск тестів
  workflow_dispatch:        # Можливість запускати вручну
    inputs:
      test_name:
        description: 'Path to test file or test name (example: app/test1.py -k test_test)'
        required: false
        default: ''

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Node.js and Allure CLI
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Allure CLI via npm
      run: |
        npm install -g allure-commandline --save-dev

    - name: Download previous Allure history
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: allure-results/history

    - name: Run tests
      run: |
        if [ -z "${{ github.event.inputs.test_name }}" ]; then
          pytest app/test1.py --alluredir=allure-results
        else
          pytest ${{ github.event.inputs.test_name }} --alluredir=allure-results
        fi
      continue-on-error: true

    - name: Generate Allure Report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Copy Allure history to results for next run
      run: |
        mkdir -p allure-results/history
        cp -r allure-report/history/* allure-results/history/ || true

    - name: Upload Allure history
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: allure-results/history

    - name: Decode JSON and authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 --decode > /tmp/gcloud-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json

    - name: Deploy Allure Report to Cloud Run
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report
        gcloud run deploy allure-report \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
