name: Run Tests and Deploy Allure Report

on:
  schedule:
    - cron: '0 0 * * *'    # Run daily at midnight
  workflow_dispatch:        # Allow manual trigger
    inputs:
      test_name:
        description: 'Path to test file or test name'
        required: false
        default: ''

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Node.js and Allure CLI
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Allure CLI via npm
      run: npm install -g allure-commandline --save-dev

    - name: Run tests
      run: |
        if [ -z "${{ github.event.inputs.test_name }}" ]; then
          pytest app/test1.py --alluredir=allure-results || true
        else
          pytest ${{ github.event.inputs.test_name }} --alluredir=allure-results || true
        fi

    - name: Try to download previous Allure history (if exists)
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: allure-history
      continue-on-error: true

    - name: Copy history to results
      run: |
        if [ -d allure-history ]; then
          cp -r allure-history/history allure-results/
        else
          echo "No previous allure-history found. Proceeding without it."
        fi

    - name: List contents of allure-results/history
      run: |
        if [ -d allure-results/history ]; then
          echo "History folder found:"
          ls -R allure-results/history
        else
          echo "No history folder found!"
        fi

    - name: Generate Allure Report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Save Allure history
      run: |
        mkdir -p allure-history
        cp -r allure-report/history allure-history/

    - name: Upload Allure history to GCS
      run: |
        echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 --decode > /tmp/gcloud-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gsutil cp -r allure-history gs://${{ secrets.GCP_BUCKET_NAME }}/allure-history/

    - name: Deploy Allure Report to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report
        gcloud run deploy allure-report \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/allure-report \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
